name: action-builder

on:
  pull_request:

jobs:
  setup-actions:
    if: ${{ contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Setup Action Builder
    runs-on: ubuntu-latest
    outputs:
      read_me_action_outcome: ${{ steps.analysis.outputs.read_me_action_outcome }}
      test_suite_action_outcome: ${{ steps.analysis.outputs.test_suite_action_outcome }}
      statics_action_outcome: ${{ steps.analysis.outputs.statics_action_outcome }}
      headers_action_outcome: ${{ steps.analysis.outputs.headers_action_outcome }}
      pr_tests_action_outcome: ${{ steps.analysis.outputs.pr_tests_action_outcome }}
      helpers_action_outcome: ${{ steps.analysis.outputs.helpers_action_outcome }}
      read_me_action_msg: ${{ steps.errors.outputs.read_me_action_msg }}
      test_suite_action_msg: ${{ steps.errors.outputs.test_suite_action_msg }}
      statics_action_msg: ${{ steps.errors.outputs.statics_action_msg }}
      headers_action_msg: ${{ steps.errors.outputs.headers_action_msg }}
      pr_tests_action_msg: ${{ steps.errors.outputs.pr_tests_action_msg }}
      helpers_action_msg: ${{ steps.errors.outputs.helpers_action_msg }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Getting File info
        run: |
          echo "${{ steps.abc.outputs.added }}"
          echo "${{ steps.abc.outputs.modified }}"
      - name: Get PR info
        run: |
          echo "${{ github.event.issue.number }}"
          echo "${{ github.event.pull_request.body }}"
          echo "${{ github.event.pull_request.title }}"
          echo "${{ github.event.pull_request.head.ref }}"
      - name: Run Action Builder
        if: ${{ always() }}
        uses: oraclecloudbricks/action_fireup@cb3f02844dbad0e9cfaf7030c0336acc52d84c53
        with:
          files_added: ${{ steps.abc.outputs.added }}
          files_modified: ${{ steps.abc.outputs.modified }}
          pr_body: ${{ github.event.pull_request.body }}
          branch_name: ${{ github.event.pull_request.head.ref }}
      - name: Overall analysis
        id: analysis
        run: |
          echo "::set-output name=read_me_action_outcome::$(jq '.[] | select(.action_name=="check_readme") | .passed' results.json)"
          echo "::set-output name=test_suite_action_outcome::$(jq '.[] | select(.action_name=="check_test_suite") | .passed' results.json)"
          echo "::set-output name=statics_action_outcome::$(jq '.[] | select(.action_name=="check_statics") | .passed' results.json)"
          echo "::set-output name=headers_action_outcome::$(jq '.[] | select(.action_name=="check_header") | .passed' results.json)"
          echo "::set-output name=pr_tests_action_outcome::$(jq '.[] | select(.action_name=="check_pr_tests") | .passed' results.json)"
          echo "::set-output name=helpers_action_outcome::$(jq '.[] | select(.action_name=="check_helpers") | .passed' results.json)"
          cat results.json
      - name: Define Errors
        id: errors
        run: |
          echo "::set-output name=read_me_action_msg::$(jq '.[] | select(.action_name=="check_readme") | .description' results.json)"
          echo "::set-output name=test_suite_action_msg::$(jq '.[] | select(.action_name=="check_test_suite") | .description' results.json)"
          echo "::set-output name=statics_action_msg::$(jq '.[] | select(.action_name=="check_statics") | .description' results.json)"
          echo "::set-output name=headers_action_msg::$(jq '.[] | select(.action_name=="check_header") | .description' results.json)"
          echo "::set-output name=pr_tests_action_msg::$(jq '.[] | select(.action_name=="check_pr_tests") | .description' results.json)"
          echo "::set-output name=helpers_action_msg::$(jq '.[] | select(.action_name=="check_helpers") | .description' results.json)"
  check-readme:
    if: ${{ contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Check README.md
    runs-on: ubuntu-latest
    needs: setup-actions
    steps:
      - name: Getting variables
        run: |
          echo "${{ needs.setup-actions.outputs.read_me_action_outcome }}"
          echo "${{ needs.setup-actions.outputs.read_me_action_msg }}"
      - name: Comment if analysis finds missing readme
        if: ${{ needs.setup-actions.outputs.read_me_action_outcome == 0}}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            :no_entry: **FAILURE: Missing README**
            :exclamation: ***The README file seems to be missing. Please add it.***
            **Error Message:**
            *${{ needs.setup-actions.outputs.read_me_action_msg }}*
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail job if Exeption appears
        if: ${{ needs.setup-actions.outputs.read_me_action_outcome == 0 }}
        run: exit 1

  check-test-suite:
    if: ${{ contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Check Test Suite
    runs-on: ubuntu-latest
    needs: setup-actions
    steps:
      - name: Getting variables
        run: |
          echo "${{ needs.setup-actions.outputs.test_suite_action_outcome }}"
          echo "${{ needs.setup-actions.outputs.test_suite_action_msg }}"
      - name: Comment if analysis finds missing test
        if: ${{ needs.setup-actions.outputs.test_suite_action_outcome == 0 }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            :no_entry: **FAILURE: Missing TEST SUITE**
            :exclamation: ***The test suite for the corresponding class seems to be missing. Please add it.***
            ***Error message:***
            *${{ needs.setup-actions.outputs.test_suite_action_msg }}*
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail job if Exeption appears
        if: ${{ needs.setup-actions.outputs.test_suite_action_outcome == 0 }}
        run: exit 1

  check-statics:
    if: ${{ contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Check Statics Entry
    runs-on: ubuntu-latest
    needs: setup-actions
    steps:
      - name: Getting variables
        run: |
          echo "${{ needs.setup-actions.outputs.statics_action_outcome }}"
          echo "${{ needs.setup-actions.outputs.statics_action_msg }}"
      - name: Comment if analysis finds missing statics entry
        if: ${{ needs.setup-actions.outputs.statics_action_outcome == 0 }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            :no_entry: **FAILURE: Missing STATICS ENTRY**
            :exclamation: ***The Statics.py file is missing entries. Please update it.***
            ***Error message:***
            *${{ needs.setup-actions.outputs.statics_action_msg }}*
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail job if Exeption appears
        if: ${{ needs.setup-actions.outputs.statics_action_outcome == 0 }}
        run: exit 1

  check-headers:
    if: ${{ contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Check Headers
    runs-on: ubuntu-latest
    needs: setup-actions
    steps:
      - name: Getting variables
        run: |
          echo "${{ needs.setup-actions.outputs.headers_action_outcome }}"
          echo "${{ needs.setup-actions.outputs.headers_action_msg }}"
      - name: Comment if analysis finds wrong headers
        if: ${{ needs.setup-actions.outputs.headers_action_outcome == 0 }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            :no_entry: **FAILURE: Wrong HEADERS FOUND**
            :exclamation: ***The class file added contains the wrong headers. Please update it.***
            ***Error message:***
            *${{ needs.setup-actions.outputs.headers_action_msg }}*
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail job if Exeption appears
        if: ${{ needs.setup-actions.outputs.headers_action_outcome == 0 }}
        run: exit 1

  check-pr-tests:
    if: ${{ contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Check PR Tests
    runs-on: ubuntu-latest
    needs: setup-actions
    steps:
      - name: Getting variables
        run: |
          echo "${{ needs.setup-actions.outputs.pr_tests_action_outcome }}"
          echo "${{ needs.setup-actions.outputs.pr_tests_action_msg }}"
      - name: Comment if analysis finds failed or missing PR Tests
        if: ${{ needs.setup-actions.outputs.pr_tests_action_outcome == 0 }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            :no_entry: **FAILURE: Missing PR TESTS**
            :exclamation: ***Some of the tests included in the PR are either missing or have failed. Please review the PR body.***
            ***Error message:***
            *${{ needs.setup-actions.outputs.pr_tests_action_msg }}*
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail job if Exeption appears
        if: ${{ needs.setup-actions.outputs.pr_tests_action_outcome == 0 }}
        run: exit 1

  check-helpers:
    if: ${{ contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Check Helpers
    runs-on: ubuntu-latest
    needs: setup-actions
    steps:
      - name: Getting variables
        run: |
          echo "${{ needs.setup-actions.outputs.helpers_action_outcome }}"
          echo "${{ needs.setup-actions.outputs.helpers_action_msg }}"
      - name: Comment if analysis finds missing retry strategy in helper
        if: ${{ needs.setup-actions.outputs.helpers_action_outcome == 0 }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            :no_entry: **FAILURE: Missing RETRY STRATEGY**
            :exclamation: ***The helper you added in helper.py seems to be missing a retry strategy. Please add it.***
            ***Error message:***
            *${{ needs.setup-actions.outputs.helpers_action_msg }}*
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail job if Exeption appears
        if: ${{ needs.setup-actions.outputs.helpers_action_outcome == 0 }}
        run: exit 1
    
  remove-log:
    if: ${{ contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Remove File
    runs-on: ubuntu-latest
    needs: [check-readme,check-test-suite,check-statics,check-headers,check-pr-tests,check-helpers]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
      env:
        ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'    
    - name: Remove file if all jobs pass
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
        
        cd test
        git rm unitary_testing.out

        git commit -m "Removing unitary_testing.out"
        git push   

  run-others:
    if: ${{ always() && !contains(github.event.pull_request.head.ref, 'feature/')}}
    name: Setup Non-Feautre Actions
    runs-on: ubuntu-latest
    outputs:
      pr_tests_outcome: ${{ steps.analysis.outputs.pr_tests_outcome }}
      pr_tests_msg: ${{ steps.errors.outputs.pr_tests_msg }}
      branch_name: ${{ github.event.pull_request.head.ref }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Getting File info
        run: |
          echo "${{ steps.abc.outputs.added }}"
          echo "${{ steps.abc.outputs.modified }}"
      - name: Get PR info
        run: |
          echo "${{ github.event.issue.number }}"
          echo "${{ github.event.pull_request.body }}"
          echo "${{ github.event.pull_request.title }}"
          echo "${{ github.event.pull_request.head.ref }}"
      - name: Run Action Builder
        if: ${{ always() }}
        uses: oraclecloudbricks/action_fireup@cb3f02844dbad0e9cfaf7030c0336acc52d84c53
        with:
          files_added: ${{ steps.abc.outputs.added }}
          files_modified: ${{ steps.abc.outputs.modified }}
          pr_body: ${{ github.event.pull_request.body }}
          branch_name: ${{ github.event.pull_request.head.ref }}
      - name: Overall analysis
        id: analysis
        run: |
          echo "::set-output name=pr_tests_outcome::$(jq '.[] | select(.action_name=="check_pr_tests") | .passed' results.json)"
          cat results.json
      - name: Define Errors
        id: errors
        run: |
          echo "::set-output name=pr_tests_msg::$(jq '.[] | select(.action_name=="check_pr_tests") | .description' results.json)"
  check-pr-tests-other:
    if: ${{ !contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Check Non-Feature Tests Pass
    runs-on: ubuntu-latest
    needs: run-others
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        env:
          ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
      - name: Getting variables
        run: |
          echo "${{ needs.run-others.outputs.pr_tests_outcome }}"
          echo "${{ needs.run-others.outputs.pr_tests_msg }}"
      - name: Comment if analysis finds failed tests
        if: ${{ needs.run-others.outputs.pr_tests_outcome == 0}}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            :no_entry: **FAILURE: Failing Tests Detected**
            :exclamation: ***There was an issue with the test file. Please review the following Error.***
            ***Error message:***
            *${{ needs.run-others.outputs.pr_tests_msg }}*
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail job if Exeption appears
        if: ${{ needs.run-others.outputs.pr_tests_outcome == 0 }}
        run: exit 1
  remove-log2:
    if: ${{ !contains(github.event.pull_request.head.ref, 'feature/') }}
    name: Remove File
    runs-on: ubuntu-latest
    needs: check-pr-tests-other
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
      env:
        ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'    
    - name: Remove file if all jobs pass
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
        
        cd test
        git rm unitary_testing.out

        git commit -m "Removing unitary_testing.out"
        git push   
